<?php
require_once dirname(__FILE__) . '/FibonacciBuzz.php';

/**
 * Test class for FibonacciBuzz.
 * Generated by PHPUnit on 2011-10-13 at 22:50:16.
 */
class FibonacciBuzzTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var FibonacciBuzz
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new FibonacciBuzz;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  public function test_渡した引数の個数分Fibonacci数のarrayをつくる()
  {
    /**
     * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55,
     * 89, 144, 233, 377, 610, 987, 1597, 2584,
     * 4181, 6765, 10946, 17711, 28657, 46368,
     * 75025, 121393, 196418, 317811, 514229,
     * 832040, 1346269, 2178309, 3524578, 5702887,
     * 9227465, 14930352, 24157817, 39088169 ...
     */
    $expect = array(1, 1, 2, 'fizz', 'buzz');
    $this->assertEquals($expect, FibonacciBuzz::FizzBuzz(5));
  }
}

