<?php
require_once dirname(__FILE__) . '/FibonacciBuzz.php';

/**
 * Test class for FibonacciBuzz.
 * Generated by PHPUnit on 2011-10-13 at 22:50:16.
 */
class FibonacciBuzzTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var FibonacciBuzz
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new FibonacciBuzz;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }
}

